[workspace]
members = [
    "crates/nest-core",
    "crates/nest-cli",
    "crates/nest-ui",
]
resolver = "2"

[workspace.package]
version = "3.0.16"
edition = "2021"
authors = ["quonaro"]
license = "MIT"

