[package]
name = "nest"
version = "0.0.1"
edition = "2021"
license = "CC-BY-NC-4.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

