[package]
name = "nestui"
version.workspace = true
edition.workspace = true

[dependencies]
nest-core = { path = "../nest-core" }
ratatui = "0.29.0"
crossterm = "0.28"
dirs = "5.0"

[[bin]]
name = "nestui"
path = "src/main.rs"
