[package]
name = "nestui"
version = "0.1.0"
edition = "2021"

[dependencies]
nest-core = { path = "../nest-core" }
ratatui = "0.29.0"
crossterm = "0.28"
dirs = "5.0"

[[bin]]
name = "nestui"
path = "src/main.rs"
