[package]
name = "nest"
version = "3.0.1"
edition = "2021"

[dependencies]
nest-core = { path = "../nest-core" }
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"

[[bin]]
name = "nest"
path = "src/main.rs"
