[package]
name = "nest"
version.workspace = true
edition.workspace = true

[dependencies]
nest-core = { path = "../nest-core" }
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
ctrlc = "3.4"

[[bin]]
name = "nest"
path = "src/main.rs"
